// SPDX-License-Identifier: Apache-2.0

package types

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"math/big"
	"os"
	"regexp"
	"strings"
	"text/template"

	"github.com/pkg/errors"
	"github.com/spf13/viper"

	wgtypes "github.com/trinitystake/dvpnd/services/wireguard/types"
	"github.com/trinitystake/dvpnd/utils"
)

var (
	ct = strings.TrimSpace(`
# Name of the network interface
interface = "{{ .Interface }}"

# Port number to accept the incoming connections
listen_port = {{ .ListenPort }}

# Server private key
private_key = "{{ .PrivateKey }}"

# Network interface that carries the node's internet traffic; peers are NAT-ed
# through it. Empty means detect it from the default route at start
uplink = "{{ .Uplink }}"

# Hand each peer an IPv6 tunnel address next to the IPv4 one; the host must
# then reach the IPv6 internet. Set it false for an IPv4-only tunnel
enable_ipv6 = {{ .EnableIPv6 }}

[obfuscation]
# AmneziaWG parameters, generated by "dvpnd amneziawg config init". Clients
# receive s1-s4 and h1-h4 in the handshake and must use the same values;
# jc/jmin/jmax are the junk packets this node sends and are per side.
# Random junk packets before the handshake: count, minimum and maximum size
jc = {{ .Obfuscation.Jc }}
jmin = {{ .Obfuscation.Jmin }}
jmax = {{ .Obfuscation.Jmax }}

# Junk prepended to the handshake initiation (s1), response (s2), cookie
# reply (s3) and transport (s4) packets; s1 + 56 must differ from s2
s1 = {{ .Obfuscation.S1 }}
s2 = {{ .Obfuscation.S2 }}
s3 = {{ .Obfuscation.S3 }}
s4 = {{ .Obfuscation.S4 }}

# Message type values replacing WireGuard's 1-4; all distinct and above 4
h1 = {{ .Obfuscation.H1 }}
h2 = {{ .Obfuscation.H2 }}
h3 = {{ .Obfuscation.H3 }}
h4 = {{ .Obfuscation.H4 }}

# Optional signature packets sent before the handshake, in AmneziaWG's tag
# syntax (e.g. "<b 0x...><r 16>"); empty means none
i1 = "{{ .Obfuscation.I1 }}"
i2 = "{{ .Obfuscation.I2 }}"
i3 = "{{ .Obfuscation.I3 }}"
i4 = "{{ .Obfuscation.I4 }}"
i5 = "{{ .Obfuscation.I5 }}"
	`)

	t = func() *template.Template {
		t, err := template.New("amneziawg_toml").Parse(ct)
		if err != nil {
			panic(err)
		}

		return t
	}()

	// iPacket is AmneziaWG's tag syntax for signature packets: a sequence of
	// <b hex>, <c>, <t>, <r n>, <rd n>, <rc n> tags.
	iPacket = regexp.MustCompile(`^(<(b 0x[0-9a-fA-F]+|c|t|r [0-9]+|rd [0-9]+|rc [0-9]+)>)+$`)
)

// Obfuscation are the AmneziaWG parameters.
type Obfuscation struct {
	Jc   uint16 `json:"jc" mapstructure:"jc"`
	Jmin uint16 `json:"jmin" mapstructure:"jmin"`
	Jmax uint16 `json:"jmax" mapstructure:"jmax"`
	S1   uint16 `json:"s1" mapstructure:"s1"`
	S2   uint16 `json:"s2" mapstructure:"s2"`
	S3   uint16 `json:"s3" mapstructure:"s3"`
	S4   uint16 `json:"s4" mapstructure:"s4"`
	H1   uint32 `json:"h1" mapstructure:"h1"`
	H2   uint32 `json:"h2" mapstructure:"h2"`
	H3   uint32 `json:"h3" mapstructure:"h3"`
	H4   uint32 `json:"h4" mapstructure:"h4"`
	I1   string `json:"i1" mapstructure:"i1"`
	I2   string `json:"i2" mapstructure:"i2"`
	I3   string `json:"i3" mapstructure:"i3"`
	I4   string `json:"i4" mapstructure:"i4"`
	I5   string `json:"i5" mapstructure:"i5"`
}

// Validate applies the constraints both sides of the tunnel check: junk sizes
// within a datagram, S1 + 56 != S2, headers all distinct and above
// WireGuard's own 1-4 (or all zero, which is plain WireGuard framing).
func (o *Obfuscation) Validate() error {
	if o.Jc > 128 {
		return errors.New("jc must be at most 128")
	}
	if o.Jmax > 1280 || o.Jmin > o.Jmax {
		return errors.New("jmin must not exceed jmax, and jmax must be at most 1280")
	}
	if o.S1 > 1132 || o.S2 > 1188 || o.S3 > 1132 || o.S4 > 1132 {
		return errors.New("s1, s3 and s4 must be at most 1132, s2 at most 1188")
	}
	if uint32(o.S1)+56 == uint32(o.S2) {
		return errors.New("s1 + 56 must not equal s2")
	}

	headers := []uint32{o.H1, o.H2, o.H3, o.H4}
	if headers[0] != 0 || headers[1] != 0 || headers[2] != 0 || headers[3] != 0 {
		seen := map[uint32]bool{}
		for _, h := range headers {
			if h <= 4 {
				return errors.New("h1-h4 must be above 4")
			}
			if seen[h] {
				return errors.New("h1-h4 must be distinct")
			}
			seen[h] = true
		}
	}

	for name, v := range o.IPackets() {
		if v != "" && !iPacket.MatchString(v) {
			return errors.Errorf("%s is not in AmneziaWG's tag syntax", name)
		}
	}

	return nil
}

// IPackets lists the signature packets by name, including empty ones.
func (o *Obfuscation) IPackets() map[string]string {
	return map[string]string{"i1": o.I1, "i2": o.I2, "i3": o.I3, "i4": o.I4, "i5": o.I5}
}

// InterfaceLines renders the parameters as awg-quick [Interface] keys.
func (o *Obfuscation) InterfaceLines() []string {
	lines := []string{
		fmt.Sprintf("Jc = %d", o.Jc),
		fmt.Sprintf("Jmin = %d", o.Jmin),
		fmt.Sprintf("Jmax = %d", o.Jmax),
		fmt.Sprintf("S1 = %d", o.S1),
		fmt.Sprintf("S2 = %d", o.S2),
		fmt.Sprintf("S3 = %d", o.S3),
		fmt.Sprintf("S4 = %d", o.S4),
		fmt.Sprintf("H1 = %d", o.H1),
		fmt.Sprintf("H2 = %d", o.H2),
		fmt.Sprintf("H3 = %d", o.H3),
		fmt.Sprintf("H4 = %d", o.H4),
	}
	for _, name := range []string{"I1", "I2", "I3", "I4", "I5"} {
		if v := o.IPackets()[strings.ToLower(name)]; v != "" {
			lines = append(lines, fmt.Sprintf("%s = %s", name, v))
		}
	}

	return lines
}

// Generate draws a fresh parameter set: a few small junk packets, padding
// on the two handshake messages, none on cookie and transport packets (which
// would cost tunnel MTU), and four distinct random headers.
func (o *Obfuscation) Generate() *Obfuscation {
	o.Jc = 4
	o.Jmin = 40
	o.Jmax = 70
	o.S1 = randomUint16(15, 150)
	for {
		o.S2 = randomUint16(15, 150)
		if uint32(o.S1)+56 != uint32(o.S2) {
			break
		}
	}
	o.S3, o.S4 = 0, 0

	seen := map[uint32]bool{}
	headers := make([]uint32, 0, 4)
	for len(headers) < 4 {
		h := randomUint32(5, 1<<31)
		if seen[h] {
			continue
		}
		seen[h] = true
		headers = append(headers, h)
	}
	o.H1, o.H2, o.H3, o.H4 = headers[0], headers[1], headers[2], headers[3]

	return o
}

func randomUint16(min, max uint16) uint16 {
	n, err := rand.Int(rand.Reader, big.NewInt(int64(max-min+1)))
	if err != nil {
		panic(err)
	}

	return min + uint16(n.Int64())
}

func randomUint32(min, max uint32) uint32 {
	var b [4]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}

	return min + binary.BigEndian.Uint32(b[:])%(max-min+1)
}

// Config is wireguard.toml's keys plus the obfuscation section.
type Config struct {
	Interface   string       `json:"interface" mapstructure:"interface"`
	ListenPort  uint16       `json:"listen_port" mapstructure:"listen_port"`
	PrivateKey  string       `json:"private_key" mapstructure:"private_key"`
	Uplink      string       `json:"uplink" mapstructure:"uplink"`
	EnableIPv6  bool         `json:"enable_ipv6" mapstructure:"enable_ipv6"`
	Obfuscation *Obfuscation `json:"obfuscation" mapstructure:"obfuscation"`
}

func NewConfig() *Config {
	return &Config{Obfuscation: &Obfuscation{}}
}

// WireGuard is the part of the configuration the WireGuard service runs on.
func (c *Config) WireGuard() *wgtypes.Config {
	return &wgtypes.Config{
		Interface:  c.Interface,
		ListenPort: c.ListenPort,
		PrivateKey: c.PrivateKey,
		Uplink:     c.Uplink,
		EnableIPv6: c.EnableIPv6,
	}
}

func (c *Config) Validate() error {
	if err := c.WireGuard().Validate(); err != nil {
		return err
	}
	if err := c.Obfuscation.Validate(); err != nil {
		return errors.Wrapf(err, "invalid section obfuscation")
	}

	return nil
}

func (c *Config) WithDefaultValues() *Config {
	key, err := wgtypes.NewPrivateKey()
	if err != nil {
		panic(err)
	}

	c.Interface = "awg0"
	c.ListenPort = utils.RandomPort()
	c.EnableIPv6 = true
	c.PrivateKey = key.String()
	c.Obfuscation.Generate()

	return c
}

func (c *Config) SaveToPath(path string) error {
	var buf bytes.Buffer
	if err := t.Execute(&buf, c); err != nil {
		return err
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}

func (c *Config) String() string {
	var buf bytes.Buffer
	if err := t.Execute(&buf, c); err != nil {
		panic(err)
	}

	return buf.String()
}

// ReadInConfig starts from static defaults, never from a generated key or
// parameter set, so a file missing a value fails validation instead of
// silently getting a fresh one.
func ReadInConfig(v *viper.Viper) (*Config, error) {
	config := NewConfig()
	config.Interface = "awg0"
	config.EnableIPv6 = true

	if err := v.ReadInConfig(); err != nil {
		return nil, err
	}
	if err := v.Unmarshal(config); err != nil {
		return nil, err
	}

	return config, nil
}
