// SPDX-License-Identifier: Apache-2.0

package types

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/pkg/errors"
	"github.com/spf13/viper"
	"golang.org/x/crypto/curve25519"

	"github.com/trinitystake/dvpnd/v9/utils"
)

var (
	ct = strings.TrimSpace(`
[vless]
# Port number to accept the incoming connections (TCP)
listen_port = {{ .VLESS.ListenPort }}

# Transport security: "tls" uses the node's tls.crt and tls.key and clients pin the
# certificate; "reality" needs no certificate and imitates the TLS handshake of the
# site named in [reality] server_name
security = "{{ .VLESS.Security }}"

# XTLS Vision flow control (recommended; every current client supports it)
flow = {{ .VLESS.Flow }}

[reality]
# Site whose TLS handshake is imitated: it must serve TLS 1.3 with HTTP/2 on port 443 and
# answer with a small certificate chain (www.apple.com and www.cloudflare.com are known to
# work with current xray; www.microsoft.com is not)
server_name = "{{ .Reality.ServerName }}"

# x25519 key pair, base64url, generated by "dvpnd xray config init"
private_key = "{{ .Reality.PrivateKey }}"
public_key = "{{ .Reality.PublicKey }}"

# Short id, up to 16 hex characters; may be empty
short_id = "{{ .Reality.ShortID }}"

# Browser TLS fingerprint clients are told to imitate
fingerprint = "{{ .Reality.Fingerprint }}"

[api]
# Loopback port on which the node drives xray; nothing else may bind it
port = {{ .API.Port }}
	`)

	t = func() *template.Template {
		t, err := template.New("xray_toml").Parse(ct)
		if err != nil {
			panic(err)
		}

		return t
	}()
)

type VLESSConfig struct {
	ListenPort uint16 `json:"listen_port" mapstructure:"listen_port"`
	Security   string `json:"security" mapstructure:"security"`
	Flow       bool   `json:"flow" mapstructure:"flow"`
}

func (c *VLESSConfig) Validate() error {
	if c.ListenPort == 0 {
		return errors.New("listen_port cannot be zero")
	}
	if c.Security != SecurityTLS && c.Security != SecurityReality {
		return fmt.Errorf("security must be %q or %q", SecurityTLS, SecurityReality)
	}

	return nil
}

type RealityConfig struct {
	ServerName  string `json:"server_name" mapstructure:"server_name"`
	PrivateKey  string `json:"private_key" mapstructure:"private_key"`
	PublicKey   string `json:"public_key" mapstructure:"public_key"`
	ShortID     string `json:"short_id" mapstructure:"short_id"`
	Fingerprint string `json:"fingerprint" mapstructure:"fingerprint"`
}

// Validate checks the reality section; the key pair must be present and
// consistent so that the public key clients are told matches the private key
// xray uses.
func (c *RealityConfig) Validate() error {
	if strings.TrimSpace(c.ServerName) == "" {
		return errors.New("server_name cannot be empty")
	}
	if strings.Contains(c.ServerName, ":") || strings.Contains(c.ServerName, "/") {
		return errors.New("server_name must be a host name without port or path")
	}

	private, err := base64.RawURLEncoding.DecodeString(c.PrivateKey)
	if err != nil || len(private) != curve25519.ScalarSize {
		return errors.New("private_key must be a base64url x25519 key")
	}

	public, err := curve25519.X25519(private, curve25519.Basepoint)
	if err != nil {
		return errors.Wrap(err, "invalid private_key")
	}
	if base64.RawURLEncoding.EncodeToString(public) != c.PublicKey {
		return errors.New("public_key does not match private_key")
	}

	if len(c.ShortID) > 16 || len(c.ShortID)%2 != 0 {
		return errors.New("short_id must be up to 16 hex characters")
	}
	if _, err := hex.DecodeString(c.ShortID); err != nil {
		return errors.New("short_id must be hex")
	}

	if c.Fingerprint == "" {
		return errors.New("fingerprint cannot be empty")
	}

	return nil
}

// Dest is the host:port xray dials to borrow the TLS handshake.
func (c *RealityConfig) Dest() string {
	return c.ServerName + ":443"
}

type APIConfig struct {
	Port uint16 `json:"port" mapstructure:"port"`
}

func (c *APIConfig) Validate() error {
	if c.Port == 0 {
		return errors.New("port cannot be zero")
	}

	return nil
}

type Config struct {
	VLESS   *VLESSConfig   `json:"vless" mapstructure:"vless"`
	Reality *RealityConfig `json:"reality" mapstructure:"reality"`
	API     *APIConfig     `json:"api" mapstructure:"api"`
}

func NewConfig() *Config {
	return &Config{
		VLESS:   &VLESSConfig{},
		Reality: &RealityConfig{},
		API:     &APIConfig{},
	}
}

func (c *Config) Validate() error {
	if err := c.VLESS.Validate(); err != nil {
		return errors.Wrapf(err, "invalid section vless")
	}
	if c.VLESS.Security == SecurityReality {
		if err := c.Reality.Validate(); err != nil {
			return errors.Wrapf(err, "invalid section reality")
		}
	}
	if err := c.API.Validate(); err != nil {
		return errors.Wrapf(err, "invalid section api")
	}

	return nil
}

// withStaticDefaults fills the values that do not involve key material; it
// is what a configuration read from disk starts from, so a file that omits a
// key never gets a silently generated one.
func (c *Config) withStaticDefaults() *Config {
	c.VLESS.ListenPort = utils.RandomPort()
	c.VLESS.Security = SecurityTLS
	c.VLESS.Flow = true
	c.Reality.ServerName = "www.apple.com"
	c.Reality.Fingerprint = "chrome"
	c.API.Port = utils.RandomPort()

	return c
}

// WithDefaultValues is what "config init" writes: static defaults plus a
// fresh reality key pair and short id.
func (c *Config) WithDefaultValues() *Config {
	c.withStaticDefaults()

	private := make([]byte, curve25519.ScalarSize)
	if _, err := rand.Read(private); err != nil {
		panic(err)
	}
	public, err := curve25519.X25519(private, curve25519.Basepoint)
	if err != nil {
		panic(err)
	}

	shortID := make([]byte, 8)
	if _, err := rand.Read(shortID); err != nil {
		panic(err)
	}

	c.Reality.PrivateKey = base64.RawURLEncoding.EncodeToString(private)
	c.Reality.PublicKey = base64.RawURLEncoding.EncodeToString(public)
	c.Reality.ShortID = hex.EncodeToString(shortID)

	return c
}

func (c *Config) SaveToPath(path string) error {
	var buf bytes.Buffer
	if err := t.Execute(&buf, c); err != nil {
		return err
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}

func (c *Config) String() string {
	var buf bytes.Buffer
	if err := t.Execute(&buf, c); err != nil {
		panic(err)
	}

	return buf.String()
}

func ReadInConfig(v *viper.Viper) (*Config, error) {
	config := NewConfig().withStaticDefaults()
	if err := v.ReadInConfig(); err != nil {
		return nil, err
	}
	if err := v.Unmarshal(config); err != nil {
		return nil, err
	}

	return config, nil
}
